### ISSUE TITLE
Windows App Certification Kit failed for WP8.1

### ISSUE THREAD

**Issue by ghost** [AArnott/pinvoke#325] opened 2017-04-19 10:37 UTC
Hi 
Thanks for the plugin.
Now I am trying to generate release build for my Xamarin.Forms winphone 8.1 project. But during the certification check, its failed with following error message. 
But its fine to deploy internal developer device. Is there any solution available?

Packages:
Xamarin.Froms ->2.3.3.193
PInovke.NCrypt & its dependencies -> 0.5.64

Error:
```
This API is not supported for this application type - Api=NCryptCreatePersistedKey. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptDecrypt. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptDeleteKey. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptDeriveKey. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptEncrypt. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptEnumAlgorithms. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptEnumKeys. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptExportKey. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptFinalizeKey. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptFreeBuffer. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptFreeObject. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptGetProperty. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptImportKey. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptIsAlgSupported. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptKeyDerivation. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptOpenKey. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptOpenStorageProvider. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptSecretAgreement. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptSetProperty. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptSignHash. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=NCryptVerifySignature. Module=ncrypt.dll. File=PInvoke.NCrypt.dll.
This API is not supported for this application type - Api=FindFirstFileEx. Module=api-ms-win-core-file-l1-2-0.dll. File=PInvoke.Kernel32.dll.
This API is not supported for this application type - Api=WaitForSingleObject. Module=api-ms-win-core-synch-l1-2-0.dll. File=PInvoke.Kernel32.dll.
This API is not supported for this application type - Api=FormatMessage. Module=api-ms-win-core-localization-l1-2-0.dll. File=PInvoke.Kernel32.dll.
This API is not supported for this application type - Api=BCryptDeriveKey. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptDestroySecret. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptEnumAlgorithms. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptFinalizeKeyPair. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptFreeBuffer. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptGenerateKeyPair. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptImportKeyPair. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptSecretAgreement. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptSignHash. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptVerifySignature. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=CancelIoEx. Module=api-ms-win-core-io-l1-1-1.dll. File=PInvoke.Kernel32.dll.
This API is not supported for this application type - Api=BCryptCloseAlgorithmProvider. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptCreateHash. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptDecrypt. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptDestroyHash. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptDestroyKey. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptEncrypt. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptExportKey. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptFinishHash. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptGenRandom. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptGenerateSymmetricKey. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptGetProperty. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptHashData. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptImportKey. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptOpenAlgorithmProvider. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
This API is not supported for this application type - Api=BCryptSetProperty. Module=bcrypt.dll. File=PInvoke.BCrypt.dll.
```

**Comment by AArnott** [comment] 2017-04-19 15:32
Dupe of #226

**Closed as completed by AArnott** 2017-04-19 15:32 UTC
