### ISSUE TITLE
GetWindowTextHelper_WithNonzeroLastError test fails

### ISSUE THREAD

**Issue by ghost** [AArnott/pinvoke#388] opened 2018-05-13 00:35 UTC
I think I understand why this is failing. 

```
            Kernel32.SetLastError(2);
            Assert.Equal(string.Empty, GetWindowText(hwnd)); <<< throws with _last error_ == 2
```
Internally, `GetWindowText(hwnd)` does this:

```
           var maxLength = GetWindowTextLength(hWnd);
            if (maxLength == 0)
            {
                var lastError = GetLastError();
                if (lastError != Win32ErrorCode.ERROR_SUCCESS)
                {
                    throw new Win32Exception(lastError);
                }

                return string.Empty;
            }
```

The problem is the Win32 `GetWindowTextLength` function, which ...

- ... wants you to check for last error if the return value is `0`
- ... but doesn't make a strong claim that a `0` return value always indicates an error condition. In other words, `0` _may be an error_, but `0` _isn't always an error_.

Something to remember about how Win32 works: If now errors need to be reported, then none are reported. So if `GetWindowTextLength` has no cause to report an error, it will not update _last erorr_ .

So imagine the following function call sequence - 

- `SetLastError(2)`
- Create an `HWND `with an empty Window Text
- Call `GetWindowTextLength `on this `HWND`
  - `GetWindowTextLength `returns `0 `
  - In this instance, `0 `is a valid _non-error_ return value
  - `GetWindowTextLength` had no cause to report errors, so it didn't update the _last-error_.
- Notice that `GetWindowTextLength `returned `0`, and so we have to call `GetLastError `to determine whether `0` means _error_, or whether `0` means _zero length text_. 
  - Unfortunately, we end up with _error code `2`_, because `GetWindowTextLength `**never overwrote the last error value we had originally set**!!

As far as I can see, this is a design flaw in the `GetWindowTextLength`'s contract. There are more functions like these, unfortunately. 

Ultimately, I don't see a way of salvaging `GetWindowTextHelper_WithNonzeroLastError` test. 

That said, User32.helpers.cs version of `GetWindowText` is probably just fine as-is. As with most things related to Win32, callers have a duty to be beware of gotchas. 

=== 

Aside:

We work around these in WPF, where we can can, by explicitly calling `SetLastError(0)` before calling such functions. This approach works reasonably well in native code, but isn't reliable for P/Invokes. For e.g., something like this isn't necessarily reliable - other actions may happen (for e.g., instigated by the Marshaler) between the call to `SetLastError `and the call to `GetWindowTextLengthInternal` that may overwrite the _last error_ from `0` to something else. 

```
        [DllImport(nameof(User32), CharSet = CharSet.Unicode, SetLastError = true, EntryPoint = "GetWindowTextLength")]
        private static extern int GetWindowTextLengthInternal(IntPtr hWnd);
        
        public static in GetWindowTextLength(IntPtr hWnd)
        {
            Kernel32.SetLastError(0);
            return GetWindowTextLengthInternal(hWnd);
        }
```

What may be most reliable is the use of a native module as a helper: 

**nativehelpermodule.dll**

```
extern "C" __declspec(dllexport) DWORD GetWindowTextLengthInternal(HWND hWnd)
{
    SetLastError(0);
    return GetWindowTextLength(hWnd);
}
```

**P/Invoke definition**
```
        [DllImport("nativehelpermodule.dll", CharSet = CharSet.Unicode, SetLastError = true, EntryPoint = "GetWindowTextLengthInternal")]
        public static extern int GetWindowTextLength(IntPtr hWnd);
```

**Comment by AArnott** [comment] 2018-05-13 05:13
This looks like an excellent write-up, but appears to be a dupe of #329. Do you agree, @vatsanm?

**Closed as completed** 2018-05-13 05:14 UTC

**Comment by ghost** [comment] 2018-05-13 15:35
You are right, it looks like the same report.
